service: parser-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  region: us-east-1
  memorySize: 256
  timeout: 10
  # Uncomment to use a specific AWS CLI profile
  # profile: your-profile-name

  httpApi:
    cors: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: 'yarn'
    excludeFiles: 'src/**/*.test.js'

functions:
  postlightParser:
    handler: src/parser.default
    events:
      - httpApi:
          path: /parser
          method: GET
      - schedule:
          rate: rate(5 minutes)
          enabled: true

  parseHtml:
    handler: src/parse-html.default
    events:
      - httpApi:
          path: /parse-html
          method: POST
      - schedule:
          rate: rate(5 minutes)
          enabled: true

plugins:
  - serverless-webpack
  - serverless-offline